[tox]
requires =
    tox-uv>=1.0
envlist =
    style
    test

[testenv]
runner = uv-venv-lock-runner

[testenv:style]
# linting checks don't need the package or dependencies installed as they scan the source tree
skip_install = true

# index-url is passed by default, trusted-host is not
# optionally allow trusted-host to be passed
passenv =
    PIP_TRUSTED_HOST
    UV_DEFAULT_INDEX
    UV_INDEX_URL
    UV_INSECURE_HOST

# must supply this as uppercase as otherwise tests fail if proxy is set
setenv =
    NO_PROXY=localhost

commands =
    ruff check
    ruff format --check
    ty check --exit-zero

[testenv:test]
# index-url is passed by default, trusted-host is not
# optionally allow trusted-host to be passed
passenv =
    PIP_TRUSTED_HOST
    UV_DEFAULT_INDEX
    UV_INDEX_URL
    UV_INSECURE_HOST
    FILE_MANAGER_VIRUSTOTAL_API_KEY
    FILE_MANAGER_AZURE_STORAGE_ACCESS_KEY
    FILE_MANAGER_AZURE_STORAGE_ACCOUNT_ADDRESS
    FILE_MANAGER_FILE_CACHE_DIR

# must supply this as uppercase as otherwise tests fail if proxy is set
setenv =
    NO_PROXY=localhost
    FILE_MANAGER_AZURE_BLOB_CACHE_ENABLED=false

dependency_groups =
    dev

commands =
    pytest --junitxml=.tox/.work_env/test-results.xml tests/
